### ISSUE TITLE
"L18/D60 CP182 3.0x" Macro error

### ISSUE THREAD

**Issue by Quetzalcoatel** [WuphonsReach/ffiv-crafting-macros#1]
The Macro "L18/D60 CP182 3.0x" needs D70:
Right now, it contains waste not, two combos of Basic Touch/ Standard touch (20 in total), then Basic Touch, Standard Touch, Basic Touch (30), leaving just 10 durability, not enough for the two Basic Synthesis, also, requiring 200CP.

To be correct with the CP182 and 3.0x, the last Basic Touch would have to be removed, I think.

**Comment by WuphonsReach** [comment]
Looking in-game...

- `/ac "Waste Not" <wait.2>` = 56 CP
- `/ac "Basic Touch" <wait.3>` = 18 CP
- `/ac "Standard Touch" <wait.3>` = 18 CP (reduced from 32 CP)
- `/ac "Basic Touch" <wait.3>` = 18 CP
- `/ac "Standard Touch" <wait.3>` = 18 CP (reduced from 32 CP)
- `/ac "Basic Touch" <wait.3>` = 18 CP
- `/ac "Standard Touch" <wait.3>` = 18 CP (reduced from 32 CP)
- `/ac "Veneration" <wait.2>` = 18 CP
- `/ac "Basic Synthesis" <wait.3>` = 0 CP
- `/ac "Basic Synthesis" <wait.3>` = 0 CP

CP = 182

And yep, I see the extra "Basic Touch" now.  I think I fixed it in-game but forgot to push my update into Github.

**Comment by WuphonsReach** [comment]
Thanks - fixed in https://github.com/WuphonsReach/ffiv-crafting-macros/commit/25167b522a36505667054f0d891f41c352b3fc72
